config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  get "pages/home" , to:"pages#home"

  # get '/recipes' , to:'recipes#index'
  # get '/recipes/new', to:'recipes#new', as:'new_recipe'
  # get '/recipes/:id', to:'recipes#show', as:'recipe'
  resources :recipes
  get 'signup', to:"chefs#new"
  resources :chefs , except:[:new]

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  resources :ingredients 
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save{self.email=email.downcase}
  validates :chefname, presence: true ,length: { maximum: 30 }
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true ,length: { maximum: 255 },
            format: {with:  VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

 has_many :recipes , dependent: :destroy   
 has_secure_password    
 validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
 has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  has_many :comments, dependent: :destroy
end
 

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

end
 

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  belongs_to :chef
  validates :chef_id, presence: true

  default_scope -> {order(updated_at: :desc)}
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
end
 

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
 belongs_to :ingredient
 belongs_to :recipe
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

  helper_method :current_chef, :logged_in?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_chef 
  end

  def require_user
    if !logged_in?
      flash[:danger]="You must be logged in to perform this action"
      redirect_to root_path
    end
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only:[:show ,:edit , :update , :destroy ]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef=Chef.new
  end

  def create
    @chef=Chef.new(chef_params)
    if @chef.save
      session[:chef_id]=@chef.id
      flash[:success]="Welcome #{@chef.chefname} to My Recipes App!"
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end

  def show 
    #@chef=Chef.find(params[:id])
    @chef_recipes= @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
    #@chef=Chef.find(params[:id])
  end

  def update
    #@chef=Chef.find(params[:id])
    if @chef.update(chef_params)
      flash[:success]="Your account was successfully updated!"
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def destroy
    #@chef=Chef.find(params[:id])
    if !chef.admin?
    @chef.destroy
    flash[:danger]="Chef and all associated recipes have been deleted"
    redirect_to chefs_path
    end
  end

  private
    def chef_params
      params.require(:chef).permit(:chefname , :email, :password , :password_confirmation)
    end

    def set_chef
      @chef=Chef.find(params[:id])
    end

    def require_same_user
      if current_chef != @chef and !current_chef.admin?
        flash[:danger]="You can edit or delete your own account"
        redirect_to chefs_path
    end 
  end

  def require_admin
    if logged_in? && !current_chef.admin?
      flash[:danger]= "Only admin user can perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only:[:edit , :update, :show]
  before_action :require_admin ,except: [:show, :index]
  def index
    @ingredients=Ingredient.paginate(page: params[:page],per_page: 5)
  end

  def new
    @ingredient=Ingredient.new
  end

  def create
    @ingredient= Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success]="Ingredient was create successfully"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def show
    @ingredient_recipes= @ingredient.recipes.paginate(page: params[:page], per_page: 5)

  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success]="Ingredient was updated successfully"
      redirect_to @ingredient
    else
      render 'edit'
    end
 
  end

  def destroy
  end

  private

  def set_ingredient
    @ingredient=Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_chef.admin?)
      flash[:danger]= "Only admin can perform this action"
      redirect_to ingredients_path
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :destroy, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
 
  def index
      @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    # @recipes= @recipes.paginate(params[:page]).per_page(5)
 end

  def show
  end

  def new
    @recipe =Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success]="Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
 
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe was deleted successfully!"
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe= Recipe.find(params[:id])
  end

  def recipe_params 
    params.require(:recipe).permit(:name , :description, ingredient_ids: [])
  end

  def require_same_user
    if current_chef != @recipe&.chef and !current_chef.admin?
      flash[:danger]="You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
   chef= Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id]=chef.id
      flash[:success]="You have successfully logged in"
      redirect_to chef
    else
      flash.now[:danger]="There was some thing wrong with your login"
      render 'new'
    end
  end

  def destroy
    session[:chef_id]=nil
    flash[:success]="You have logged out"
    redirect_to root_path
  end

end
 

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
  end
end
 

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef  %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :chefname ,"Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your Name", autofocus: true %>
        </div>
      </div>

      
      <div class="form-group">
        <div  class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email,class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>


     <div class="form-group">
        <div  class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password,class: "form-control", placeholder: "Enter your password" %>
        </div>
      </div>


       <div class="form-group">
        <div  class="control-label col-md-2">
          <%= f.label :password_confirmation ,"Confirm Password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation ,class: "form-control", placeholder: "Confirm your Password" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@chef.new_record? ? "Sign Up": "Update Account", 
                                            class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch"> 
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title' ,title:"Edit your Profile" %>

<%= render 'form' %> 

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "Showing all Chefs" %>

<div align="center">
<%= will_paginate @chefs %>
  <% @chefs.each do |chef| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4-offset-4">
          <li> <%= link_to gravatar_for(chef), chef_path(chef) %> </li>
          <li class="chef-title"> <%= link_to chef.chefname.capitalize, chef_path(chef) %> </li>
          <li> <small> <%= pluralize(chef.recipes.count, "recipes") if chef.recipes %> </small> </li>
       <%# <li> <%= link_to "Delete this chef", chef_path(chef),  method: :delete,  data: {confirm: "Are you sure you want to delete this chef and all associated recipes?"} %> </li> 
        <% if logged_in? && current_chef.admin? && !chef.admin? %>
        <li><%= link_to 'Delete this Chef', chef_path(chef), data: { "turbo-method": :delete , turbo_confirm: 'Are you sure?'  } %></li>
        <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @chefs %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title' ,title:"Sign up for application" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title' ,title:"Welcome #{@chef.chefname}'s profile" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 150 %>
 
  </div>
</div>
  <% if @chef.recipes.count != 0 %>
   <h4 align="center"> <%=@chef.chefname %>'s Recipes </h4>
  <div align="center">
   <%= will_paginate  @chef_recipes %>
  </div>
    <%= render 'recipes/recipe', obj: @chef_recipes %> 
  <div align="center">
   <%= will_paginate  @chef_recipes %>
  </div>
  <% else %>
  <h4 align='center'>No recipes yet!!</h4>

  <% end %>

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter Ingredient", autofocus: true %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@ingredient.new_record? ? "Add Ingredient": "Update Ingredient",
                       class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"> <% link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span> 

app/views/ingredients/edit.html.erb
<%=render 'shared/page_title',title: "Edit Ingredient name" %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<div align="center">
<%= will_paginate @chefs %>
  <% @ingredients.each do |ing| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4-offset-4">
          <li class="chef-title"> <%= link_to ing.name.capitalize, ingredient_path(ing) %> </li>
          <li> <small> <%= pluralize(ing.recipes.count, "recipes") if ing.recipes %> </small> </li>
       <%# <li> <%= link_to "Delete this chef", chef_path(chef),  method: :delete,  data: {confirm: "Are you sure you want to delete this chef and all associated recipes?"} %> </li> 
        <% if logged_in? && current_chef.admin?  %>
        <li><%= link_to 'Edit this Ingredient', edit_ingredient_path(ing) %></li>
        <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @chefs %>
</div>

app/views/ingredients/new.html.erb
<%=render 'shared/page_title',title: "Enter a new Ingredient" %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title' ,title:"#{@ingredient.name}" %>

  <% if @ingredient.recipes.count != 0 %>
   <h4 align="center">Recipes containing <%= @ingredient.name %></h4>
  <div align="center">
   <%= will_paginate  @ingredient_recipes %>
  </div>
    <%= render 'recipes/recipe', obj: @ingredient_recipes %> 
  <div align="center">
   <%= will_paginate  @ingredient_recipes %>
  </div>
  <% else %>
  <h4 align='center'>No recipes yet!!</h4>

  <% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Chefs", chefs_path  %> </li>
         <li> <%= link_to "All Recipes", recipes_path  %> </li>
         <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create a new Recipe",new_recipe_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      <% end %>
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Ingredients",ingredients_path %></li>
            
            <% Ingredient.all.each do |ingredient| %>
             <li><%= link_to ingredient.name.capitalize ,ingredient_path(ingredient) %></li>

            <% end %>
            <% if logged_in? && current_chef.admin? %>

            <li role="separator" class="divider"></li>
            <li><%= link_to "New Ingredient", new_ingredient_path %></li>
           <% end %>
          </ul>
        </li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%# <li><%= link_to "Login"  ,login_path </li>  %>
       <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_chef.chefname.capitalize %>' Profile  <%= "Admin" if current_chef.admin? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to "View your Profie",chef_path(current_chef) %> </li>
              <li><%= link_to "Edit your Profie",edit_chef_path(current_chef) %> </li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li> <%= link_to "Logout", logout_path , data: { "turbo-method": :delete } %>  </li>
            <%# <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %> 

          </ul>
        </li>
        <% else %>
        <li> <%= link_to "Login",login_path %> </li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home Page</h1>

<div class="jumbotron center ">
<h1>Welcome to MyRecipes</h1>
<h2>The best recipes sharing app!</h2>
<p> <%= link_to "Sign up for App",signup_path, class: "btn btn-danger btn-lg btn-xlarge" %> </p>
</div>

<div class="row">
  <div class="col-lg-4">
    <h2>Safari bug warning!</h2>
      <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>

      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>


      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_inbox") {cb.check_box(class: "checkbox")+ cb.text}  %>
            <% end %>
          </div>     
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
      <%= gravatar_for(recipe.chef, size: 120) %>
        
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name , recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>

      <% if recipe.ingredients.any? %>
      <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %> </small></span>
      </p> 
      <% if logged_in? && (current_chef==recipe.chef || current_chef.admin? )%>
      <div class="recipe-action">
            <%= link_to "Edit this recipe" ,edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
      <%# <%= link_to "Delete this recipe Rails 5", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete?" },class: "btn btn-xs btn-danger" %>  
      <%= link_to 'Delete this recipe', recipe_path(recipe), data: { "turbo-method": :delete , turbo_confirm: 'Are you sure?'  } ,class: "btn btn-xs btn-danger"%>
      
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
 <%= render 'shared/page_title', title: "Edit a existing recipe" %>


  <%= render 'form' %> 

app/views/recipes/index.html.erb
<h1>Recipes Index Page</h1>

<%= render 'shared/page_title', title: "Showing all recipes" %>
<div align="center">
  <%= will_paginate @recipes %>
</div>
<%= render 'recipe' ,obj: @recipes %>

<div align="center">
  <%= will_paginate @recipes %>
</div> 

app/views/recipes/show.html.erb
<h1>Show</h1>

<%= render 'shared/page_title', title: @recipe.name %>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />

  <% if @recipe.ingredients.any? %>
  <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <%= simple_format(@recipe.description) %>
  <hr />
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
  </p>
  <p class="center">
    <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
  </p>
    <p class="center">
    <small><%= @recipe.chef.chefname.capitalize %> </small> 
    <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
  </p>
   </div>
   <div class="recipe-actions">
    <%  if logged_in? && (current_chef == @recipe.chef || current_chef.admin? ) %>
      <%= link_to "Edit this recipe" ,edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
      <%# <%= link_to "Delete this recipe Rails 5", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete?" },class: "btn btn-xs btn-danger" %>  
      <%= link_to 'Delete this recipe', recipe_path(@recipe), data: { "turbo-method": :delete , turbo_confirm: 'Are you sure?'  } ,class: "btn btn-xs btn-danger"%>
    <% end %>
     <%= link_to "Return to recipe listing" ,recipes_path, class: "btn btn-xs btn-primary" %>
   </div>
  
</div> 